In [1]:
import numpy as np
import pandas as pd

In [2]:
# pip install keras

Note: you may need to restart the kernel to use updated packages.


In [2]:
import matplotlib #импорт библиотеки для графиков
import matplotlib.pyplot as plt #использование переменной plt дляиспользования библиотеки matplotlib
matplotlib.style.use('ggplot')#загружаем стили для графиков
#корректное отображение графиков в Jupyter
%matplotlib inline

In [3]:
# !pip install keras
# !pip install tensorflow

In [9]:
# !pip install np_utils

     |████████████████████████████████| 61 kB 378 kB/s eta 0:00:01
  Created wheel for np-utils: filename=np_utils-0.6.0-py3-none-any.whl size=56447 sha256=647ec765a139959c06935884a1205084d69b02afcdc515f05efea5c176b7080e
  Stored in directory: /Users/leonid/Library/Caches/pip/wheels/55/8b/e7/a23fd46c709c21e3e6fcb55978d88b018f80d54018459978c3
Successfully built np-utils


# ! Мне помогла команда ниже и версия питона 3.10.9

In [11]:
# pip install numpy==1.21


     |████████████████████████████████| 16.9 MB 1.8 MB/s eta 0:00:01
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.1
    Uninstalling numpy-1.24.1:
      Successfully uninstalled numpy-1.24.1
Note: you may need to restart the kernel to use updated packages.


In [5]:
from keras.models import Sequential 
from keras.layers import Dense 
from keras.utils import np_utils

In [6]:
wine=pd.read_csv('/Users/leonid/Downloads/Wine.txt',sep='\t',header=0)
wine.head()

Input1  Input2  Input3  Input4  Input5  Input6  Input7  Input8  Input9  \
0   14.23    1.71    2.43    15.6     127    2.80    3.06    0.28    2.29   
1   13.20    1.78    2.14    11.2     100    2.65    2.76    0.26    1.28   
2   13.16    2.36    2.67    18.6     101    2.80    3.24    0.30    2.81   
3   14.37    1.95    2.50    16.8     113    3.85    3.49    0.24    2.18   
4   13.24    2.59    2.87    21.0     118    2.80    2.69    0.39    1.82   

   Input10  Input11  Input12  Input13  Desired1(3)  
0     5.64     1.04     3.92     1065            0  
1     4.38     1.05     3.40     1050            0  
2     5.68     1.03     3.17     1185            0  
3     7.80     0.86     3.45     1480            0  
4     4.32     1.04     2.93      735            0

In [8]:
#смотрим соотношение элементов в последнем стобце
wine['Desired1(3)'].value_counts(normalize=True)

2    0.398876
0    0.331461
1    0.269663
Name: Desired1(3), dtype: float64

In [13]:
#  предикторы и отклик разделяем
# Отклик - группирующая переменная -  вектор y
y=wine['Desired1(3)']
# Предикторы - таблица X
X=wine.drop('Desired1(3)',axis=1)


In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=1234)

In [16]:
#Cмотрим количество элементов в каждой выборке

#X_train и y_train - обучаем на этих выборках
#X_test и y_test - тестируем точность на тренированной модели на этой выборке

X_train.head()

Input1  Input2  Input3  Input4  Input5  Input6  Input7  Input8  Input9  \
93    12.29    2.83    2.22    18.0      88    2.45    2.25    0.25    1.99   
11    14.12    1.48    2.32    16.8      95    2.20    2.43    0.26    1.57   
153   13.23    3.30    2.28    18.5      98    1.80    0.83    0.61    1.87   
74    11.96    1.09    2.30    21.0     101    3.38    2.14    0.13    1.65   
162   12.85    3.27    2.58    22.0     106    1.65    0.60    0.60    0.96   

     Input10  Input11  Input12  Input13  
93      2.15     1.15     3.30      290  
11      5.00     1.17     2.82     1280  
153    10.52     0.56     1.51      675  
74      3.21     0.99     3.13      886  
162     5.58     0.87     2.11      570

In [18]:
X_test.head()

Input1  Input2  Input3  Input4  Input5  Input6  Input7  Input8  Input9  \
111   12.52    2.43    2.17    21.0      88    2.55    2.27    0.26    1.22   
123   13.05    5.80    2.13    21.5      86    2.62    2.65    0.30    2.01   
63    12.37    1.13    2.16    19.0      87    3.50    3.10    0.19    1.87   
88    11.64    2.06    2.46    21.6      84    1.95    1.69    0.48    1.35   
141   13.36    2.56    2.35    20.0      89    1.40    0.50    0.37    0.64   

     Input10  Input11  Input12  Input13  
111     2.00     0.90     2.78      325  
123     2.60     0.73     3.10      380  
63      4.45     1.22     2.87      420  
88      2.80     1.00     2.75      680  
141     5.60     0.70     2.47      780

In [19]:
y_train.head()

93     2
11     0
153    1
74     2
162    1
Name: Desired1(3), dtype: int64

In [20]:
y_test.head()

111    2
123    2
63     2
88     2
141    1
Name: Desired1(3), dtype: int64

In [21]:
#  Преобразование pandas dataframe в numpy array
X_train=X_train.values
X_test=X_test.values
y_train=y_train.values
y_test=y_test.values

In [22]:
# Больше 2-х классов
# Классы не упорядочены
# np_utils делает преобразование в бинарную матрицу
y_train_bin=np_utils.to_categorical(y_train)

y_test_bin=np_utils.to_categorical(y_test)

In [24]:
# Почемунеработает? - !Это не датафрейм
y_train_bin.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [27]:
#После конвертации в тензоры, классы 0,1,2 стали набором
# нолей и единиц, 1,0,0 - 0-ойкласс, 0,1,0 - 2й, 0,0,1 - 3-й    
y_train_bin[0:5]

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]], dtype=float32)

In [29]:
# Создание модели и указание параметров
model=Sequential()
#Добавляемслой 9 нейронов, 13 параметровнавход, используемакт. функ. relu
model.add(Dense(9,input_dim=13,activation='relu'))
#на скрытых слоях мы не указываем сколько параметров подается на вход, используем softmax
model.add(Dense(10,activation='relu',))
model.add(Dense(3,activation='softmax'))

# Построениемодели (методминим., критерийкач., метрика)
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

# Запусктренировкимодели, указываемколичествоэпоха
model.fit(X_train,y_train_bin,epochs=300,batch_size=10)

Epoch 1/300
14/14 [==============================] - 1s 5ms/step - loss: 49.1002 - accuracy: 0.2632
Epoch 2/300
14/14 [==============================] - 0s 2ms/step - loss: 29.4839 - accuracy: 0.3008
Epoch 3/300
14/14 [==============================] - 0s 5ms/step - loss: 16.1871 - accuracy: 0.2406
Epoch 4/300
14/14 [==============================] - 0s 2ms/step - loss: 6.0377 - accuracy: 0.1805
Epoch 5/300
14/14 [==============================] - 0s 2ms/step - loss: 4.6683 - accuracy: 0.2331
Epoch 6/300
14/14 [==============================] - 0s 3ms/step - loss: 4.1663 - accuracy: 0.0902
Epoch 7/300
14/14 [==============================] - 0s 3ms/step - loss: 3.6132 - accuracy: 0.0677
Epoch 8/300
14/14 [==============================] - 0s 2ms/step - loss: 1.8596 - accuracy: 0.2030
Epoch 9/300
14/14 [==============================] - 0s 3ms/step - loss: 1.3575 - accuracy: 0.3609
Epoch 10/300
14/14 [==============================] - 0s 3ms/step - loss: 1.1695 - accuracy: 0.4962
Epoch 

Epoch 83/300
14/14 [==============================] - 0s 1ms/step - loss: 0.3030 - accuracy: 0.9173
Epoch 84/300
14/14 [==============================] - 0s 2ms/step - loss: 0.3074 - accuracy: 0.9098
Epoch 85/300
14/14 [==============================] - 0s 2ms/step - loss: 0.3384 - accuracy: 0.8722
Epoch 86/300
14/14 [==============================] - 0s 2ms/step - loss: 0.3307 - accuracy: 0.9098
Epoch 87/300
14/14 [==============================] - 0s 2ms/step - loss: 0.2944 - accuracy: 0.9173
Epoch 88/300
14/14 [==============================] - 0s 2ms/step - loss: 0.3056 - accuracy: 0.9173
Epoch 89/300
14/14 [==============================] - 0s 2ms/step - loss: 0.2861 - accuracy: 0.9323
Epoch 90/300
14/14 [==============================] - 0s 1ms/step - loss: 0.3226 - accuracy: 0.8947
Epoch 91/300
14/14 [==============================] - 0s 1ms/step - loss: 0.3151 - accuracy: 0.9023
Epoch 92/300
14/14 [==============================] - 0s 1ms/step - loss: 0.3011 - accuracy: 0.8947


14/14 [==============================] - 0s 2ms/step - loss: 0.1787 - accuracy: 0.9549
Epoch 165/300
14/14 [==============================] - 0s 1ms/step - loss: 0.1688 - accuracy: 0.9624
Epoch 166/300
14/14 [==============================] - 0s 1ms/step - loss: 0.2052 - accuracy: 0.9398
Epoch 167/300
14/14 [==============================] - 0s 1ms/step - loss: 0.1797 - accuracy: 0.9398
Epoch 168/300
14/14 [==============================] - 0s 1ms/step - loss: 0.2172 - accuracy: 0.9398
Epoch 169/300
14/14 [==============================] - 0s 1ms/step - loss: 0.1795 - accuracy: 0.9398
Epoch 170/300
14/14 [==============================] - 0s 2ms/step - loss: 0.1444 - accuracy: 0.9699
Epoch 171/300
14/14 [==============================] - 0s 2ms/step - loss: 0.1621 - accuracy: 0.9549
Epoch 172/300
14/14 [==============================] - 0s 2ms/step - loss: 0.1674 - accuracy: 0.9398
Epoch 173/300
14/14 [==============================] - 0s 2ms/step - loss: 0.1813 - accuracy: 0.9398
Epoc

14/14 [==============================] - 0s 2ms/step - loss: 0.1241 - accuracy: 0.9549
Epoch 246/300
14/14 [==============================] - 0s 2ms/step - loss: 0.1472 - accuracy: 0.9474
Epoch 247/300
14/14 [==============================] - 0s 2ms/step - loss: 0.1108 - accuracy: 0.9549
Epoch 248/300
14/14 [==============================] - 0s 2ms/step - loss: 0.1214 - accuracy: 0.9699
Epoch 249/300
14/14 [==============================] - 0s 2ms/step - loss: 0.1263 - accuracy: 0.9624
Epoch 250/300
14/14 [==============================] - 0s 2ms/step - loss: 0.1193 - accuracy: 0.9474
Epoch 251/300
14/14 [==============================] - 0s 2ms/step - loss: 0.1117 - accuracy: 0.9699
Epoch 252/300
14/14 [==============================] - 0s 2ms/step - loss: 0.1276 - accuracy: 0.9549
Epoch 253/300
14/14 [==============================] - 0s 2ms/step - loss: 0.1080 - accuracy: 0.9699
Epoch 254/300
14/14 [==============================] - 0s 2ms/step - loss: 0.1183 - accuracy: 0.9699
Epoc

In [30]:
# Оценкамодели
scores=model.evaluate(X_test,y_test_bin)
print("\nТочность: %.2f%%"%(scores[1]*100))

2/2 [==============================] - 0s 5ms/step - loss: 0.1754 - accuracy: 0.9778

Точность: 97.78%


In [32]:
# Вычисляемпредсказания. смотрим какие бы получились y-ки по X-ам
predictions=model.predict(X_test)
print(predictions[0:5])

2/2 [==============================] - 0s 4ms/step
[[1.4706848e-04 1.2382570e-03 9.9861467e-01]
 [5.4062223e-03 2.0713322e-02 9.7388047e-01]
 [1.8822623e-03 4.3340900e-04 9.9768436e-01]
 [3.5448454e-02 3.9331880e-03 9.6061844e-01]
 [2.0413530e-01 6.9704133e-01 9.8823398e-02]]
